"""Campaign schemas — a campaign is a named bulk lead push.

Each lead in a campaign goes through the exact same validation and dispatch
path as a single POST /leads push; the campaign row only groups them and
carries batch-level aggregates for the console.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CampaignStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"


class CampaignLeadInput(BaseModel):
    """One row of the uploaded list. customer_mobile_number is mandatory;
    every other key rides along in the lead payload (template schema
    validation still applies per lead)."""

    payload: Dict[str, Any]
    request_id: Optional[str] = Field(
        None, description="Optional per-row order/request id; autogenerated if absent"
    )


class CreateCampaignRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=255)
    template_id: str
    reseller_id: str
    merchant_id: Optional[str] = None
    leads: List[CampaignLeadInput] = Field(..., min_length=1)


class CampaignLeadError(BaseModel):
    row: int
    reason: str


class Campaign(BaseModel):
    id: str
    reseller_id: str
    merchant_id: Optional[str] = None
    template_id: str
    name: str
    status: CampaignStatus
    total_leads: int
    created_by: Optional[str] = None
    created_at: datetime
    updated_at: datetime


class CampaignStats(BaseModel):
    """Live aggregates over the campaign's leads."""

    total: int = 0
    backlog: int = 0
    processing: int = 0
    finished: int = 0
    dialed: int = 0  # leads with at least one attempt
    picked: int = 0  # finished leads whose outcome is not NO_ANSWER
    outcome_counts: Dict[str, int] = Field(default_factory=dict)


class CampaignWithStats(BaseModel):
    campaign: Campaign
    stats: CampaignStats


class CreateCampaignResponse(BaseModel):
    campaign: Campaign
    queued: int
    skipped: List[CampaignLeadError] = Field(default_factory=list)


class CampaignListResponse(BaseModel):
    campaigns: List[CampaignWithStats]
    total: int
    page: int
    limit: int


class StopCampaignResponse(BaseModel):
    campaign: Campaign
    aborted_leads: int
