"""
Configuration constants for field value discovery functionality.
Contains dimension aliases and fallback field values for Juspay analytics.
"""

# Dimension alias mappings for field value discovery
DIMENSION_ALIASES = {
    "payment_provider": "payment_gateway",
    "gateway": "payment_gateway", 
    "card_network": "card_brand",
    "card_provider": "card_brand",
    "is_stored_card_transaction": "token_repeat",
    "transaction_via_saved_card": "token_repeat",
}

# Fallback field values for common dimensions when API calls fail
FIELD_GUARDS = {
   "actual_order_status":[
      "COD_INITIATED",
      "AUTHORIZED",
      "AUTO_REFUNDED",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "CAPTURE_FAILED",
      "AUTHORIZING",
      "VOIDED",
      "NEW",
      "SUCCESS",
      "PENDING_AUTHENTICATION",
      "AUTHORIZATION_FAILED",
      "PARTIAL_CHARGED",
      "JUSPAY_DECLINED",
      "TO_BE_CHARGED"
   ],
   "actual_payment_status":[
      "COD_INITIATED",
      "PENDING_VBV",
      "AUTHORIZED",
      "CHARGED",
      "FAILURE",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "CAPTURE_FAILED",
      "AUTHORIZING",
      "VOIDED",
      "AUTO_REFUNDED",
      "VBV_SUCCESSFUL",
      "AUTHORIZATION_FAILED",
      "STARTED",
      "JUSPAY_DECLINED",
      "TO_BE_CHARGED"
   ],
   "allowed_requeue":[
      
   ],
   "auth_type":[
      "THREE_DS_2",
      "THREE_DS",
      "MOTO",
      "OTP",
      "THREE_DS2"
   ],
   "bank":[
      "PhonePe",
      "GooglePay",
      "Paytm",
      "UPI",
      "HDFC Bank",
      "Cash",
      "Axis Bank",
      "ICICI Bank",
      "SBI",
      "ybl",
      "Cred Pay",
      "PAY",
      "BHIM",
      "Amazon Pay",
      "Kotak Mahindra Bank",
      "oksbi",
      "Sodexo",
      "SIMPL Pay Later",
      "okhdfcbank",
      "okicici",
      "okaxis",
      "Mobikwik",
      "axl",
      "ibl",
      "RBL Bank",
      "AMEX",
      "IndusInd Bank",
      "IDFC FIRST Bank",
      "Bank Of Baroda",
      "One Card",
      "LAZYPAY",
      "ptsbi",
      "Union Bank of India",
      "HSBC Bank",
      "Canara Bank",
      "Yes Bank",
      "FamApp",
      "Federal Bank",
      "upi",
      "CRED_UPI",
      "Airtel Payments Bank",
      "fam",
      "Punjab National Bank",
      "ptyes",
      "Navi",
      "Twid Reward",
      "Standard Chartered Bank",
      "ptaxis",
      "pthdfc",
      "AU Small Finance Bank",
      "Indian Bank",
      "Bank of India",
      "Jammu and Kashmir Bank",
      "jupiteraxis",
      "Indian Overseas Bank",
      "AMAZONPAY_V2",
      "kotak",
      "axisb",
      "DBS Bank",
      "WhatsApp",
      "apl",
      "IDBI Bank",
      "Central Bank of India",
      "Tri O Tech Solutions Private Limited",
      "Bank of Maharashtra",
      "pz",
      "CITI Bank",
      "NAV_AGENT_WALLET",
      "SBM Bank India",
      "CRED_CARD",
      "hdfcbank",
      "UCO Bank",
      "UPI_PAY",
      "PayZapp",
      "null",
      "Freecharge",
      "ikwik",
      "PayPay Wallet",
      "India Post Payments Bank",
      "Chase Bank",
      "Karur Vysya Bank",
      "Bajaj Finserv",
      "South Indian Bank",
      "Slice Card",
      "axisbank",
      "APPLEPAY",
      "amazonpay",
      "City Union Bank",
      "yapl",
      "Jupiter Money",
      "pingpay",
      "Karnataka Bank",
      "JioMoney",
      "jio",
      "TRANSCORP INTERNATIONAL",
      "EMIRATES NBD BANK (P.J.S.C.)",
      "Punjab and Sind Bank",
      "slice",
      "cnrb",
      "The Catholic Syrian Bank",
      "Bandhan Bank",
      "VNPAY Wallet",
      "ABU DHABI COMMERCIAL BANK",
      "airtel",
      "pnb",
      "Saraswat Bank",
      "abfspay",
      "postbank",
      "BOB Card",
      "TORONTO-DOMINION BANK, THE",
      "Kiwi",
      "Snapmint",
      "Tamilnad Mercantile Bank",
      "Punjab National Bank Corporate",
      "Equitas Bank",
      "JP Morgan",
      "sliceaxis",
      "UPI_QR",
      "COMMONWEALTH BANK OF AUSTRALIA",
      "Samsung Pay",
      "E_COLLECT",
      "dbs",
      "CAPITAL ONE, NATIONAL ASSOCIATION",
      "DCB",
      "Scotia Bank",
      "ShopSe",
      "Capital One Bank",
      "axio",
      "tapicici",
      "Fino Payments Bank",
      "Deutsche Bank",
      "Olamoney",
      "barodampay",
      "Eroute Technologies",
      "BANK OF AMERICA - CONSUMER CREDIT",
      "Transcrop Bank",
      "MASHREQBANK",
      "federal",
      "LivQuik",
      "Barclays Bank",
      "MONZO BANK LIMITED",
      "Bank of America",
      "MAHARASHTRA GRAMIN BANK",
      "MALAYAN BANKING BERHAD",
      "Ujjivan Small Finance Bank",
      "COLLECT",
      "goaxb",
      "REVOLUT LTD",
      "AL RAJHI BANKING AND INVESTMENT CORP.",
      "waaxis",
      "Fi Money",
      "uboi",
      "FIRST ABU DHABI BANK PJSC",
      "waicici",
      "REVOLUT BANK UAB",
      "TATAPAY Wallet",
      "EMIRATES NBD",
      "Groww",
      "EMIRATES ISLAMIC BANK P.J.S.C.",
      "Baroda UP Bank",
      "TataNeu",
      "EARLYSALARY Loan Service Provider",
      "GOLDMAN SACHS BANK USA",
      "omni",
      "Wells Fargo Bank",
      "E_BANK",
      "Omni Card",
      "Abhyudaya Cooperative Bank",
      "LOYALTY COINS",
      "The Cosmos Cooperative Bank",
      "CANADIAN IMPERIAL BANK OF COMMERCE",
      "WISE EUROPE SA/NV",
      "rapl",
      "PATHWARD, N.A.",
      "SUTTON BANK",
      "yesg",
      "CIMB BANK BERHAD",
      "NATIONAL BANK OF RAS AL-KHAIMAH (RAKBANK)",
      "COMMUNITY FEDERAL SAVINGS BANK",
      "NSDL Payments Bank",
      "Westpac Bank",
      "Dhanalakshmi Bank",
      "Make My Trip",
      "THANE DISTRICT CENTRAL COOPERATIVE BANK",
      "wahdfcbank",
      "ROYAL BANK OF CANADA",
      "Allahabad Bank",
      "PAYPAL",
      "MI Pay",
      "ABU DHABI ISLAMIC BANK",
      "DUBAI ISLAMIC BANK",
      "Union Bank Corporate Banking",
      "hsbc",
      "Loantap",
      "REVOLUT LIMITED",
      "Kerala Gramin Bank",
      "Jana Small Finance Bank",
      "ePaylater",
      "THE TORONTO-DOMINION BANK",
      "indianbank",
      "sib",
      "Andhra Bank",
      "TJSB",
      "UNITED OVERSEAS BANK LIMITED",
      "AIRWALLEX (NETHERLANDS) B.V.",
      "Bank of Baroda Corporate",
      "THE SAUDI NATIONAL BANK",
      "SIMPL_PAYINTHREE",
      "SAUDI AWWAL BANK",
      "rbl",
      "WISE PAYMENTS LIMITED",
      "The Shamrao Vithal Cooperative Bank",
      "LLOYDS BANK PLC",
      "Utkarsh Small Finance Bank",
      "ITAU UNIBANCO S.A.",
      "Bharat Bank",
      "Bassein Catholic Bank",
      "BANCO DE LA PROVINCIA DE BUENOS AIRES",
      "centralbank",
      "Axis Corporate Netbanking",
      "MASTERCARD INTERNATIONAL",
      "NATIONAL AUSTRALIA BANK LIMITED",
      "aubank",
      "KOHO FINANCIAL INCORPORATED",
      "ESAF Small Finance Bank",
      "Sarva Haryana Gramin Bank",
      "BANK ISLAM MALAYSIA BERHAD",
      "VARO BANK, NATIONAL ASSOCIATION",
      "THE BANCORP BANK, NATIONAL ASSOCIATION",
      "FINCARE SMALL FINANCE BANK",
      "COMMERCIAL BANK OF QATAR Q.S.C",
      "Baroda Rajasthan Kshetriya Gramin Bank",
      "PROVISIONAL - FIRST ABU DHABI BANK (PJSC)",
      "N26 BANK AG",
      "Royal Bank of Scotland",
      "COMPROPAGO S.A. DE C.V., I.F.P.E.",
      "NAVY FEDERAL CREDIT UNION",
      "GP Parsik Bank",
      "SYNCHRONY BANK",
      "TRI O TECH SOLUTIONS PRIVATE LIMITED",
      "Dakshin Bihar Gramin",
      "Finsall Lender Service Provider",
      "US Bank",
      "BANKMUSCAT (SAOG)",
      "RHB BANK BERHAD",
      "COMMERCIAL BANK OF DUBAI(PSC)",
      "BANK SIMPANAN NASIONAL",
      "EBIX PAYMENT SERVICES",
      "RING",
      "COASTAL COMMUNITY BANK",
      "WISE AUSTRALIA PTY LTD",
      "fbl",
      "NORDEA BANK ABP",
      "Bank of Bahrain and Kuwait",
      "Shamrao Vithal Coop(Corporate)",
      "Karnataka Gramin Bank",
      "REAP TECHNOLOGIES LIMITED",
      "STARLING BANK LIMITED",
      "CITIZENS BANK GUYANA INC.",
      "THE KANGRA CENTRAL COOPERATIVE BANK",
      "boi",
      "BANK OF SCOTLAND PLC",
      "Rajasthan Marudhara Gramin Bank",
      "PUBLIC BANK BERHAD",
      "yesbank",
      "SUMITOMO MITSUI CARD COMPANY LIMITED",
      "LIVQUIK TECHNOLOGY INDIA",
      "The Nainital Bank",
      "OVERSEA-CHINESE BANKING CORPORATION LTD.",
      "BNEXT ELECTRONIC ISSUER, E.D.E., S.L.",
      "Postpe",
      "Andhra Pragathi Grameena Bank",
      "Ebix",
      "scb",
      "BNP Paribas",
      "CREDIT MUTUEL ARKEA",
      "BANK OF MONTREAL",
      "Andhra Pradesh Grameena Vikas Bank",
      "THE SURAT DISTRICT COOPERATIVE BANK",
      "CHOICE FINANCIAL GROUP",
      "TAMIL NADU GRAMA BANK",
      "STC BANK",
      "BHARATI SAHAKARI BANK",
      "CareemPay",
      "unionbank",
      "ANZ BANK NEW ZEALAND LIMITED",
      "J And K Grameen Bank",
      "TRUST BANK SINGAPORE LIMITED",
      "BANK OF MALDIVES PLC",
      "Nkgsb Cooperative Bank",
      "GX BANK BERHAD",
      "CREDIT AGRICOLE SOCIETE ANONYME",
      "THE MUNICIPAL COOPERATIVE BANK",
      "NATIONAL WESTMINSTER BANK PLC",
      "Janata Sahakari Bank",
      "COMMERCIAL BANK OF DUBAI",
      "DEUTSCHE KREDITBANK AG",
      "PUNE DISTRICT CENTRAL COOPERATIVE BANK",
      "Kalyan Janata Sahakari Bank",
      "SANTANDER UK PLC",
      "Jio Payments Bank Limited",
      "Kalupur Bank",
      "Bangiya Gramin Vikas Bank",
      "ODISHA GRAMYA BANK",
      "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)",
      "PEOPLES TRUST COMPANY",
      "Tamil Nadu State Apex Coop Bank",
      "TANGERINE BANK",
      "ALINMA BANK",
      "TYMEBANK LIMITED",
      "CHAITANYA GODAVARI GRAMEENA BANK",
      "Prathama Up Gramin Bank",
      "Transcorp International",
      "CITIZEN CREDIT COOPERATIVE BANK",
      "State Bank of Mauritius",
      "CELTIC BANK",
      "Corporation Bank",
      "THE KARAD URBAN COOPERATIVE BANK",
      "kbl",
      "SUNRATE SOLUTIONS LIMITED",
      "BPCE",
      "ADVANZIA BANK S.A.",
      "THE COMMERCIAL BANK OF QATAR (Q.S.C.)",
      "ALLIED IRISH BANKS, P.L.C.",
      "THE MEGHALAYA COOPERATIVE APEX BANK",
      "PNC BANK, NATIONAL ASSOCIATION",
      "THE HINDUSTHAN COOPERATIVE BANK",
      "ITAU UNIBANCO HOLDING S.A.",
      "RIYAD BANK",
      "MORROW BANK ASA",
      "YOU TECHNOLOGIES GROUP (SINGAPORE) PTE. LTD.",
      "Chamoli Zila Sahakari Bank",
      "ST. GEORGE BANK LIMITED",
      "ALBERTA TREASURY BRANCHES",
      "ASB BANK",
      "WIO BANK P.J.S.C",
      "HONG LEONG BANK BERHAD",
      "United Bank Of India",
      "UPI_COLLECT",
      "BOURSORAMA BANQUE",
      "AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED",
      "STRIPE PAYMENTS UK LIMITED",
      "ASSAM GRAMIN VIKAS BANK",
      "THE HIMACHAL PRADESH STATE COOPERATIVE BANK",
      "SHINHAN BANK",
      "JILA SAHAKARI KENDRIYA BANK",
      "OkCredit",
      "CREDIT AGRICOLE S.A.",
      "BARODA GUJARAT GRAMIN BANK",
      "BANCO MULTIPLE BHD, S. A.",
      "KLARNA BANK AB",
      "BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA",
      "THE GUJARAT STATE COOPERATIVE BANK",
      "ALLY BANK",
      "CENTRAL TRUST BANK, THE",
      "NKGSB COOPERATIVE BANK",
      "PRATHAMA UP GRAMIN BANK",
      "BANK KERJASAMA RAKYAT MALAYSIA BERHAD",
      "MAX IT FINANCE LTD",
      "Doha Bank",
      "TRIPLINK INTERNATIONAL CO.,LIMITED",
      "IDBI Bank Corporate",
      "QATAR NATIONAL BANK (Q.P.S.C.)",
      "JHARKHAND RAJYA GRAMIN BANK",
      "PRESIDENT'S CHOICE BANK",
      "BANK OF MISSOURI, THE",
      "Madhyanchal Gramin Bank",
      "ING BANK N.V.",
      "Thane Bharat Sahakari Bank",
      "EMIGRANT BANK",
      "TRIPURA GRAMIN BANK",
      "Goibibo",
      "NETWORK INTERNATIONAL LLC",
      "SUMITOMO MITSUI CARD COMPANY, LIMITED",
      "Uttarakhand Gramin Bank",
      "MONEYVIEW Loan Service Provider",
      "PATRIOT BANK, NATIONAL ASSOCIATION",
      "AL HILAL BANK PJSC",
      "Chhattisgarh Rajya Gramin Bank",
      "GREEN DOT BANK DBA BONNEVILLE BANK",
      "ICICI Bank Corporate",
      "The Surat Peoples Cooperative Bank",
      "Ellaquai Dehati Bank",
      "THE BANK OF NOVA SCOTIA",
      "PUNJAB GRAMIN BANK",
      "BENDIGO AND ADELAIDE BANK LIMITED",
      "NATIONAL BANK OF KUWAIT, S.A.K.",
      "Karnataka Vikas Grameena Bank",
      "COMMERCIAL BANK OF CEYLON PLC",
      "STRIDE BANK, NATIONAL ASSOCIATION",
      "DUKHAN BANK",
      "ING BANK (AUSTRALIA) LIMITED",
      "Oriental Bank Of Commerce",
      "HDFC Cardless",
      "BNP PARIBAS",
      "Varachha Co-operative Bank",
      "JANAKALYAN SAHAKARI BANK",
      "U.S. BANK NATIONAL ASSOCIATION-CREDIT",
      "CANADIAN TIRE BANK",
      "Livquik Technology India",
      "Pine Labs",
      "RAIGANJ CENTRAL COOPERATIVE BANK",
      "THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK",
      "GULF BANK K.S.C., THE",
      "PATHWARD, NATIONAL ASSOCIATION",
      "THE GREATER BOMBAY COOPERATIVE BANK",
      "RAJKOT NAGARIK SAHAKARI BANK",
      "YesPay",
      "ISRACARD LTD.",
      "TD BANK, NATIONAL ASSOCIATION",
      "ARAB NATIONAL BANK",
      "CITI COMMERCIAL",
      "DIGITAL COMMERCE BANK",
      "NATIONWIDE BUILDING SOCIETY",
      "Apna Sahakari Bank",
      "ASSAM COOPERATIVE APEX BANK",
      "DOHA BANK Q.S.C",
      "North Kanara GSB",
      "KASPI BANK JSC",
      "TRANSERV",
      "One Mobikwik Systems Ltd",
      "Syndicate Bank",
      "NABIL BANK LTD.",
      "PREPAY TECHNOLOGIES LTD",
      "Utkal Grameen Bank",
      "Capital Small Finance Bank",
      "Karur Vysya Corporate Banking",
      "CHARLES SCHWAB BANK, SSB",
      "MAURITIUS COMMERCIAL BANK LIMITED, THE",
      "BANQUE ISLAMIQUE DE MAURITANIE",
      "Mehsana Urban Co. Op. Bank",
      "NEO FINANCIAL TECHNOLOGIES INC",
      "INTERNATIONAL CARD SERVICES BV",
      "TELENGANA GRAMEENA BANK",
      "OVERSEA-CHINESE BANKING CORPORATION LIMITED",
      "UNITED OVERSEAS BANK (MALAYSIA) BHD",
      "THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED",
      "CJSC INTERNATIONAL BANK OF TAJIKISTAN",
      "AEON FINANCIAL SERVICE CO., LTD.",
      "BANKOFHAWAII",
      "AMBANK (M) BERHAD",
      "SOFI BANK, N.A.",
      "SHARJAH ISLAMIC BANK PJSC",
      "AL ANSARI EXCHANGE LLC",
      "STANDARD BANK OF SOUTH AFRICA, LTD.",
      "WISE PAYMENTS CANADA INC.",
      "DEUTSCHER SPARKASSEN- UND GIROVERBAND",
      "Paschim Banga Gramin Bank",
      "CAIXABANK S.A.",
      "ENTERCARD GROUP AB",
      "MIZORAM RURAL BANK",
      "DNB BANK ASA",
      "SOCIETE GENERALE S.A.",
      "MOBILEPE FINTECH BANK",
      "REVOLUT TECHNOLOGIES SINGAPORE PTE LTD.",
      "AL BILAD BANK",
      "J AND K GRAMEEN BANK",
      "WISE ASIA-PACIFIC PTE. LTD.",
      "Pay Point India Network",
      "BANK OF MALDIVES (PLC) LTD.",
      "THE ALMORA URBAN COOPERATIVE BANK",
      "Avanse Financial Services",
      "North East Small Finance Bank",
      "TRUIST BANK",
      "Premium E Business Venture",
      "BANK OF THE PHILIPPINE ISLANDS",
      "BHARATX",
      "FIRSTRAND BANK LIMITED",
      "BANK MUAMALAT MALAYSIA BERHAD",
      "USAA FEDERAL SAVINGS BANK - CREDIT",
      "COMMERZBANK AG",
      "EML PAYMENT SOLUTIONS LIMITED",
      "THE BANCORP BANK NATIONAL ASSOCIATION",
      "timecosmos",
      "The Kerala State Cooperative Bank",
      "Dombivli Nagari Sahakari Bank",
      "SWASTH_POINTS",
      "FIFTH THIRD BANK, THE",
      "WISE BRASIL PAGAMENTOS LTDA.",
      "TRIPURA STATE COOPERATIVE BANK",
      "BIGPAY MALAYSIA SDN. BHD.",
      "ZILA SAHAKARI BANK",
      "TELANGANA STATE COOPERATIVE APEX BANK",
      "REGIONS BANK",
      "KASIKORNBANK PUBLIC COMPANY LIMITED",
      "DISCOVER NETWORK",
      "RAJARAMBAPU SAHAKARI BANK",
      "CORNER BANCA S.A.",
      "The Gadchiroli District Central Cooperative Bank",
      "UBS SWITZERLAND AG",
      "BANQUE SAUDI FRANSI",
      "LATITUDE FINANCE AUSTRALIA",
      "FLAGSTAR BANK,N.A",
      "APNA SAHAKARI BANK",
      "Zila Sahakari Bank",
      "Euronet Services India Pvt Ltd",
      "GARAGEPRENEURS INTERNET PRIVATE LIMITED",
      "FLORIDA CAPITAL BANK, NATIONAL ASSOCIATION",
      "THE SATARA DISTRICT CENTRAL CO-OPERATIVE BANK LTD"
   ],
   "card_brand":[
      "CHINAUNIONPAY",
      "UNIONPAY",
      "DISCOVER",
      "RUPAY",
      "MAESTRO",
      "JCB",
      "DINERS",
      "MASTERCARD",
      "AMEX",
      "VISA",
      "SODEXO",
      "MADA",
      "BAJAJ",
      "QWIKCILVER"
   ],
   "card_type":[
      "RTP",
      "WALLET",
      "OTC",
      "REWARD",
      "DEBIT",
      "NB",
      "AADHAAR",
      "UPI",
      "CREDIT",
      "VIRTUAL_ACCOUNT"
   ],
   "emi":[
      "false",
      "true"
   ],
   "emi_tenure":[
      "12",
      "48",
      "36",
      "24",
      "6",
      "0",
      "3",
      "18",
      "9"
   ],
   "emi_type":[
      "JUSPAY_NO_COST_EMI",
      "NO_COST_EMI",
      "STANDARD_EMI",
      "LOW_COST_EMI",
      "JUSPAY_NO_COST_EMI_SPLIT"
   ],
   "entire_payment_flow":[
      "EMANDATE_PAYMENT",
      "INTENT",
      "SURCHARGE",
      "SR_BASED_ROUTING",
      "ELIMINATION_BASED_ROUTING",
      "PAYMENT_PAGE",
      "PP_QUICKPAY",
      "EMANDATE_REGISTER",
      "COLLECT",
      "REDIRECT_DEBIT",
      "MERCHANT_MANAGED_DEBIT",
      "CARD_3DS2",
      "CVVLESS",
      "NETWORK_TOKEN_USED",
      "CARD_3DS",
      "QR",
      "OFFER",
      "INAPP",
      "INAPP_REPEAT_PAY",
      "PUSH_PAY",
      "DOTP",
      "SODEXO_TOKEN_USED",
      "CREDIT_CARD_ON_UPI",
      "DIRECT_DEBIT",
      "ALTID",
      "NEW_CARD",
      "INAPP_DEBIT",
      "SILENT_RETRY",
      "PL_BASED_ROUTING",
      "RISK_CHECK",
      "INAPP_NEW_PAY",
      "MANDATE_PAYMENT",
      "NETWORK_TOKEN_CREATED",
      "ISSUER_TOKEN_USED",
      "LOCKER_TOKEN_USED",
      "SPLIT_SETTLEMENT",
      "TPV",
      "ONE_TIME_MANDATE",
      "PG_FAILURE_FALLBACK_DOTP_TO_3DS",
      "PAYMENT_CHANNEL_FALLBACK_DOTP_TO_3DS",
      "CARD_MOTO",
      "PREAUTH",
      "DECIDER_FALLBACK_DOTP_TO_3DS",
      "PAYMENT_COLLECTION_LINK",
      "SPLIT_PAYMENT",
      "ISSUER_TOKEN_CREATED",
      "LOCKER_TOKEN_CREATED",
      "NO_COST_EMI",
      "STANDARD_EMI",
      "TOKENIZATION_CONSENT_FALLBACK_DOTP_TO_3DS",
      "AUTH_PROVIDER_FALLBACK_3DS2_TO_3DS",
      "PREPAID_INSTRUMENT_ON_UPI",
      "CUSTOMER_FALLBACK_DOTP_TO_3DS",
      "PARTIAL_CAPTURE",
      "MUTUAL_FUND",
      "PP_RETRY",
      "PAYMENT_FORM",
      "PAYMENT_LINK",
      "SI_HUB",
      "INTERNAL_NO_COST_EMI",
      "ASYNC",
      "INTERNAL_NO_COST_EMI_SPLIT",
      "FRICTIONLESS_3DS",
      "DIRECT_BANK_EMI",
      "CROSS_BORDER_PAYMENT"
   ],
   "industry":[
      "NBFC",
      "Travel",
      "Education",
      "Food Delivery",
      "Others",
      "Hyperlocal",
      "Billpay",
      "EPharma",
      "TravelOrStay",
      "OTT",
      "eCommerce",
      "ERetail",
      "Ticketing",
      "Grocery Delivery",
      "Telecom / D2H",
      "Fintech",
      "Ticket Booking",
      "E-pharma",
      "Telecom",
      "Gaming",
      "Classified",
      "Investments",
      "Insurance"
   ],
   "is_business_retry":[
      "false",
      "true"
   ],
   "is_cvv_less_txn":[
      "true"
   ],
   "is_offer_txn":[
      "false",
      "true"
   ],
   "is_requeued_order":[
      "false",
      "true"
   ],
   "is_retargeted_order":[
      "false",
      "true"
   ],
   "is_retried_order":[
      "false",
      "true"
   ],
   "is_technical_retry":[
      "false",
      "true"
   ],
   "is_token_bin":[
      "FALSE",
      "TRUE"
   ],
   "is_tokenized":[
      "false",
      "true"
   ],
   "issuer_token_reference":[
      "false",
      "true"
   ],
   "mandate_feature":[
      "DISABLED",
      "OPTIONAL",
      "REQUIRED"
   ],
   "order_source_object":[
      "PAYMENT_LINK",
      "PAYMENT_FORM"
   ],
   "order_source_object_id":[
      "pf_e2c79ac0e4",
      "45ded11c587a4d67b50540ce476a5c7d",
      "pf_6dd12b8acf",
      "pf_f5fad4b9d2",
      "DASHBOARD",
      "pf_59866c9894",
      "pf_5089b50928",
      "pf_a61ccef16d",
      "pf_4e821fe74a"
   ],
   "order_status":[
      "FAILURE",
      "SUCCESS",
      "PENDING"
   ],
   "order_type":[
      "MANDATE_PAYMENT",
      "ORDER_PAYMENT",
      "TPV_MANDATE_REGISTER",
      "TPV_PAYMENT",
      "MOTO_PAYMENT",
      "VAN_PAYMENT",
      "MANDATE_REGISTER",
      "TPV_MANDATE_PAYMENT"
   ],
   "os":[
      
   ],
   "payment_gateway":[
      "INDUS_PAYU",
      "JIOPAY",
      "EPAYLATER",
      "GPAY_IMF",
      "TWOC_TWOP",
      "TATANEU",
      "ATOM",
      "MPGS",
      "YES_BIZ",
      "BOKU",
      "PAYFORT",
      "ADYEN",
      "EBS_V3",
      "HDFC",
      "SODEXO",
      "WORLDPAY",
      "CITRUS",
      "HYPER_PG",
      "HYPERPAY",
      "SHOPSE",
      "MERCHANT_CONTAINER",
      "SBI",
      "YESBANK_UPI",
      "TATAPAY",
      "LOANTAP",
      "HYPERPG",
      "TWID",
      "HDFC_UPI",
      "PAYGLOCAL",
      "RBL_BIZ",
      "AXIS_UPI",
      "CRED",
      "HDFCBANK_SMARTGATEWAY",
      "SIKA_SIMPL",
      "AIRPAY",
      "TABBY",
      "BHARATX",
      "SNAPMINT",
      "LOTUSPAY",
      "LINEPAY",
      "MOBIKWIK",
      "ITZCASH",
      "CAPITALFLOAT",
      "HDFC_CC_EMI",
      "TWID_V2",
      "STRIPE",
      "DUMMY",
      "EASEBUZZ",
      "ICICINB",
      "CAMSPAY",
      "HSBC_UPI",
      "PAYTM",
      "YPP",
      "CCAVENUE_V2",
      "PAYZAPP",
      "TATAPAYLATER",
      "CYBERSOURCE",
      "NOON",
      "PAYU",
      "CASH",
      "PINELABS",
      "PAY10",
      "LAZYPAY",
      "GOCASHFREE",
      "FREECHARGE",
      "AIRTELMONEY",
      "XENDIT",
      "PAYPAL",
      "RAZORPAY",
      "IPG",
      "FAWRYPAY",
      "PHONEPE",
      "TPSL",
      "GOOGLEPAY",
      "ZAAKPAY",
      "ICICI_UPI",
      "CAREEMPAY",
      "AMAZONPAY",
      "LSP",
      "BAJAJFINSERV",
      "NAVITAIRE",
      "CHECKOUT",
      "KBANK",
      "DIGIO",
      "MORPHEUS",
      "IATAPAY",
      "AMEX",
      "BILLDESK",
      "PAYTM_V2",
      "TATA_PA",
      "HDFCNB",
      "AIRWALLEX",
      "AXIS_BIZ",
      "SIMPL",
      "PINELABS_ONLINE"
   ],
   "payment_instrument_group":[
      "CREDIT CARD",
      "RTP",
      "WALLET",
      "OTC",
      "REWARD",
      "NET BANKING",
      "CASH",
      "AADHAAR",
      "DEBIT CARD",
      "UPI",
      "VIRTUAL_ACCOUNT"
   ],
   "payment_method_subtype":[
      "TOKENIZATION_CONSENT_FALLBACK_TO_THREE_DS",
      "VAN_NB",
      "UPI_INAPP",
      "CRED_INTENT",
      "PG_FAILURE_FALLBACK_TO_THREE_DS",
      "PUSH_PAY",
      "AUTH_PROVIDER_FALLBACK_TO_THREE_DS",
      "UPI_PAY",
      "TXN_SUB_DETAIL",
      "DECIDER_FALLBACK_TO_THREE_DS",
      "UPI_COLLECT",
      "DIRECT_WALLET_DEBIT",
      "CUSTOMER_FALLBACK_TO_THREE_DS",
      "CRED_COLLECT",
      "MANDATE",
      "REDIRECT_WALLET_DEBIT",
      "PAYMENT_CHANNEL_FALLBACK_TO_THREE_DS",
      "UPI_QR"
   ],
   "payment_method_type":[
      "RTP",
      "WALLET",
      "CARD",
      "OTC",
      "REWARD",
      "NB",
      "CASH",
      "AADHAAR",
      "CONSUMER_FINANCE",
      "MERCHANT_CONTAINER",
      "UPI",
      "VIRTUAL_ACCOUNT"
   ],
   "payment_status":[
      "FAILURE",
      "SUCCESS",
      "PENDING"
   ],
   "platform":[
      "ANDROID",
      "WEB:unknown",
      "MOBILE_WEB",
      "WEB",
      "IOS"
   ],
   "prev_order_status":[
      "AUTHORIZED",
      "AUTO_REFUNDED",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "SUCCESS",
      "AUTHORIZING",
      "PENDING_AUTHENTICATION",
      "AUTHORIZATION_FAILED",
      "JUSPAY_DECLINED"
   ],
   "prev_txn_status":[
      "PENDING_VBV",
      "AUTHORIZED",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "VOID_INITIATED",
      "AUTHORIZING",
      "VBV_SUCCESSFUL",
      "AUTHORIZATION_FAILED",
      "STARTED",
      "PENDING"
   ],
   "previous_order_status":[
      "AUTHORIZED",
      "AUTO_REFUNDED",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "SUCCESS",
      "AUTHORIZING",
      "PENDING_AUTHENTICATION",
      "AUTHORIZATION_FAILED",
      "JUSPAY_DECLINED"
   ],
   "previous_txn_status":[
      "PENDING_VBV",
      "AUTHORIZED",
      "AUTHENTICATION_FAILED",
      "CAPTURE_INITIATED",
      "VOID_INITIATED",
      "AUTHORIZING",
      "VBV_SUCCESSFUL",
      "AUTHORIZATION_FAILED",
      "STARTED",
      "PENDING"
   ],
   "status_sync_source":[
      "TRANSACTION",
      "SN_FORCE_SYNC_V1",
      "START_PAY",
      "CRON_SYNC",
      "REDIRECTION",
      "PT_SYNC",
      "ASN_FORCE_SYNC_V1",
      "WEBHOOKS"
   ],
   "stored_card_vault_provider":[
      "ALT_ID",
      "ISSUER_CARD",
      "ISSUER_TOKEN",
      "NETWORK_TOKEN",
      "SODEXO"
   ],
   "ticket_size":[
      "101-200",
      "201-300",
      ">1L",
      "1K-2K",
      "2K-5K",
      "0-100",
      "5K-10K",
      "501-1K",
      "10K-50K",
      "301-400",
      "401-500",
      "50K-1L"
   ],
   "token_repeat":[
      "FALSE",
      "TRUE"
   ],
   "tokenization_consent":[
      "false",
      "true"
   ],
   "tokenization_consent_ui_presented":[
      "false",
      "true"
   ],
   "tokenization_eligibility":[
      "Eligible",
      "NotEligible"
   ],
   "tokenized_flow":[
      "false",
      "true"
   ],
   "txn_conflict":[
      "RESOLVED",
      "CONFLICTED",
      "MATCH"
   ],
   "txn_flow_type":[
      "QR",
      "DIRECT_DEBIT",
      "NET_BANKING",
      "NATIVE",
      "CARD_TRANSACTION",
      "INAPP_DEBIT",
      "COLLECT",
      "AADHAAR_PAY",
      "REDIRECT_DEBIT",
      "EMI",
      "CASH_PAY",
      "INTENT"
   ],
   "txn_latency_enum":[
      "10M-1H",
      "1H-1D",
      "5M-6M",
      "9M-10M",
      "1M-2M",
      "1D-3D",
      "8M-9M",
      "4M-5M",
      "7M-8M",
      "3D-7D",
      "6M-7M",
      "3M-4M",
      "2M-3M",
      "0M-1M"
   ],
   "txn_object_type":[
      "MANDATE_PAYMENT",
      "ORDER_PAYMENT",
      "TPV_EMANDATE_PAYMENT",
      "EMANDATE_REGISTER",
      "TPV_PAYMENT",
      "VAN_PAYMENT",
      "MANDATE_REGISTER",
      "EMANDATE_PAYMENT",
      "TPV_EMANDATE_REGISTER",
      "PARTIAL_CAPTURE"
   ],
   "txn_source_object":[
      "TOKENIZATION_CONSENT_FALLBACK_TO_THREE_DS",
      "VAN_NB",
      "UPI_INAPP",
      "CRED_INTENT",
      "PG_FAILURE_FALLBACK_TO_THREE_DS",
      "PUSH_PAY",
      "AUTH_PROVIDER_FALLBACK_TO_THREE_DS",
      "UPI_PAY",
      "TXN_SUB_DETAIL",
      "DECIDER_FALLBACK_TO_THREE_DS",
      "UPI_COLLECT",
      "DIRECT_WALLET_DEBIT",
      "CUSTOMER_FALLBACK_TO_THREE_DS",
      "CRED_COLLECT",
      "MANDATE",
      "REDIRECT_WALLET_DEBIT",
      "PAYMENT_CHANNEL_FALLBACK_TO_THREE_DS",
      "UPI_QR"
   ],
   "txn_type":[
      "AUTH_AND_SETTLE",
      "PREAUTH_AND_SETTLE",
      "AUTH_AND_SPLIT_SETTLE"
   ],
   "unified_response_category":[
      "",
      "USER_ERROR",
      "GENERIC_ERROR",
      "GATEWAY_VALIDATION_ERROR",
      "BUSINESS_ERROR",
      "VALIDATION_ERROR",
      "PAYMENT_FAILURE",
      "NOT_FOUND",
      "TECHNICAL_ERROR",
      "USER_DROPPED",
      "GATEWAY_ERROR",
      "UNKNOWN",
      "TXN_PENDING"
   ],
   "user_opt_in":[
      "Consent Page Not Shown",
      "Skipped",
      "Approved"
   ],
   "using_stored_card":[
      "false",
      "true"
   ],
   "using_token":[
      "True",
      "False"
   ],
   "is_upicc":[
      "false",
      "true"
   ]
}