name: Build & Push Docker Image to GCR

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/745400138007/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@breeze-uat-453414.iam.gserviceaccount.com"

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gcr.io/breeze-uat-453414/clairvoyance:${{ github.event.release.tag_name }}